version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd2024
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    command: 
      - /opt/mssql/bin/sqlservr
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd2024' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      timeout: 3s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  sqlserver_data:
  redis_data: